package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

/**
 * A generated by hbm2java
 */
public class A implements java.io.Serializable {

	private Integer id;
	private Q qByQuestId;
	private Q qByQuestId_1;
	private String answerName;
	private String postedBy;

	public A() {
	}

	public A(Q qByQuestId, Q qByQuestId_1, String answerName, String postedBy) {
		this.qByQuestId = qByQuestId;
		this.qByQuestId_1 = qByQuestId_1;
		this.answerName = answerName;
		this.postedBy = postedBy;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Q getqByQuestId() {
		return this.qByQuestId;
	}

	public void setqByQuestId(Q qByQuestId) {
		this.qByQuestId = qByQuestId;
	}

	public Q getqByQuestId_1() {
		return this.qByQuestId_1;
	}

	public void setqByQuestId_1(Q qByQuestId_1) {
		this.qByQuestId_1 = qByQuestId_1;
	}

	public String getAnswerName() {
		return this.answerName;
	}

	public void setAnswerName(String answerName) {
		this.answerName = answerName;
	}

	public String getPostedBy() {
		return this.postedBy;
	}

	public void setPostedBy(String postedBy) {
		this.postedBy = postedBy;
	}

}
