package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

/**
 * An generated by hbm2java
 */
public class An implements java.io.Serializable {

	private Integer id;
	private Qu quByQuestionId;
	private Qu quByQuestId;
	private Qu quByQid;
	private String answerName;
	private String postedBy;

	public An() {
	}

	public An(Qu quByQuestionId, Qu quByQuestId, Qu quByQid, String answerName, String postedBy) {
		this.quByQuestionId = quByQuestionId;
		this.quByQuestId = quByQuestId;
		this.quByQid = quByQid;
		this.answerName = answerName;
		this.postedBy = postedBy;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Qu getQuByQuestionId() {
		return this.quByQuestionId;
	}

	public void setQuByQuestionId(Qu quByQuestionId) {
		this.quByQuestionId = quByQuestionId;
	}

	public Qu getQuByQuestId() {
		return this.quByQuestId;
	}

	public void setQuByQuestId(Qu quByQuestId) {
		this.quByQuestId = quByQuestId;
	}

	public Qu getQuByQid() {
		return this.quByQid;
	}

	public void setQuByQid(Qu quByQid) {
		this.quByQid = quByQid;
	}

	public String getAnswerName() {
		return this.answerName;
	}

	public void setAnswerName(String answerName) {
		this.answerName = answerName;
	}

	public String getPostedBy() {
		return this.postedBy;
	}

	public void setPostedBy(String postedBy) {
		this.postedBy = postedBy;
	}

}
