package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int id;
	private int duration;
	private String name;
	private Set students = new HashSet(0);
	private Set studentCourses = new HashSet(0);

	public Course() {
	}

	public Course(int id, int duration) {
		this.id = id;
		this.duration = duration;
	}

	public Course(int id, int duration, String name, Set students, Set studentCourses) {
		this.id = id;
		this.duration = duration;
		this.name = name;
		this.students = students;
		this.studentCourses = studentCourses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

	public Set getStudentCourses() {
		return this.studentCourses;
	}

	public void setStudentCourses(Set studentCourses) {
		this.studentCourses = studentCourses;
	}

}
