package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cust generated by hbm2java
 */
public class Cust implements java.io.Serializable {

	private Integer id;
	private Itm itm;
	private String name;
	private Set itms = new HashSet(0);

	public Cust() {
	}

	public Cust(Itm itm, String name, Set itms) {
		this.itm = itm;
		this.name = name;
		this.itms = itms;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Itm getItm() {
		return this.itm;
	}

	public void setItm(Itm itm) {
		this.itm = itm;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getItms() {
		return this.itms;
	}

	public void setItms(Set itms) {
		this.itms = itms;
	}

}
