package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

/**
 * DepartEmployee generated by hbm2java
 */
public class DepartEmployee implements java.io.Serializable {

	private DepartEmployeeId id;
	private Employe employe;
	private Depart depart;

	public DepartEmployee() {
	}

	public DepartEmployee(DepartEmployeeId id, Employe employe, Depart depart) {
		this.id = id;
		this.employe = employe;
		this.depart = depart;
	}

	public DepartEmployeeId getId() {
		return this.id;
	}

	public void setId(DepartEmployeeId id) {
		this.id = id;
	}

	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	public Depart getDepart() {
		return this.depart;
	}

	public void setDepart(Depart depart) {
		this.depart = depart;
	}

}
