package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Depart generated by hbm2java
 */
public class Depart implements java.io.Serializable {

	private int id;
	private String name;
	private Set departEmployees = new HashSet(0);
	private Set employes = new HashSet(0);

	public Depart() {
	}

	public Depart(int id) {
		this.id = id;
	}

	public Depart(int id, String name, Set departEmployees, Set employes) {
		this.id = id;
		this.name = name;
		this.departEmployees = departEmployees;
		this.employes = employes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDepartEmployees() {
		return this.departEmployees;
	}

	public void setDepartEmployees(Set departEmployees) {
		this.departEmployees = departEmployees;
	}

	public Set getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set employes) {
		this.employes = employes;
	}

}
