package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

/**
 * DepartEmployeeId generated by hbm2java
 */
public class DepartEmployeeId implements java.io.Serializable {

	private int departmantId;
	private int employeeId;

	public DepartEmployeeId() {
	}

	public DepartEmployeeId(int departmantId, int employeeId) {
		this.departmantId = departmantId;
		this.employeeId = employeeId;
	}

	public int getDepartmantId() {
		return this.departmantId;
	}

	public void setDepartmantId(int departmantId) {
		this.departmantId = departmantId;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepartEmployeeId))
			return false;
		DepartEmployeeId castOther = (DepartEmployeeId) other;

		return (this.getDepartmantId() == castOther.getDepartmantId())
				&& (this.getEmployeeId() == castOther.getEmployeeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDepartmantId();
		result = 37 * result + this.getEmployeeId();
		return result;
	}

}
