package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Depa generated by hbm2java
 */
public class Depa implements java.io.Serializable {

	private int id;
	private String name;
	private Set employes = new HashSet(0);
	private Set emplos = new HashSet(0);
	private Set depaEmployees = new HashSet(0);

	public Depa() {
	}

	public Depa(int id) {
		this.id = id;
	}

	public Depa(int id, String name, Set employes, Set emplos, Set depaEmployees) {
		this.id = id;
		this.name = name;
		this.employes = employes;
		this.emplos = emplos;
		this.depaEmployees = depaEmployees;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set employes) {
		this.employes = employes;
	}

	public Set getEmplos() {
		return this.emplos;
	}

	public void setEmplos(Set emplos) {
		this.emplos = emplos;
	}

	public Set getDepaEmployees() {
		return this.depaEmployees;
	}

	public void setDepaEmployees(Set depaEmployees) {
		this.depaEmployees = depaEmployees;
	}

}
