package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

/**
 * Em1 generated by hbm2java
 */
public class Em1 implements java.io.Serializable {

	private Em1Id id;

	public Em1() {
	}

	public Em1(Em1Id id) {
		this.id = id;
	}

	public Em1Id getId() {
		return this.id;
	}

	public void setId(Em1Id id) {
		this.id = id;
	}

}
