package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Emplo generated by hbm2java
 */
public class Emplo implements java.io.Serializable {

	private int id;
	private Depa depa;
	private String name;
	private Set depaEmployees = new HashSet(0);

	public Emplo() {
	}

	public Emplo(int id) {
		this.id = id;
	}

	public Emplo(int id, Depa depa, String name, Set depaEmployees) {
		this.id = id;
		this.depa = depa;
		this.name = name;
		this.depaEmployees = depaEmployees;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Depa getDepa() {
		return this.depa;
	}

	public void setDepa(Depa depa) {
		this.depa = depa;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDepaEmployees() {
		return this.depaEmployees;
	}

	public void setDepaEmployees(Set depaEmployees) {
		this.depaEmployees = depaEmployees;
	}

}
