package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

/**
 * Empl generated by hbm2java
 */
public class Empl implements java.io.Serializable {

	private EmplId id;

	public Empl() {
	}

	public Empl(EmplId id) {
		this.id = id;
	}

	public EmplId getId() {
		return this.id;
	}

	public void setId(EmplId id) {
		this.id = id;
	}

}
