package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Employe generated by hbm2java
 */
public class Employe implements java.io.Serializable {

	private int id;
	private Depa depart;
	private String name;
	private Set depaEmployees = new HashSet(0);
	private Set departEmployees = new HashSet(0);

	public Employe() {
	}

	public Employe(int id) {
		this.id = id;
	}

	public Employe(int id, Depa depart, String name, Set depaEmployees, Set departEmployees) {
		this.id = id;
		this.depart = depart;
		this.name = name;
		this.depaEmployees = depaEmployees;
		this.departEmployees = departEmployees;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Depa getDepart() {
		return this.depart;
	}

	public void setDepart(Depa depart) {
		this.depart = depart;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDepaEmployees() {
		return this.depaEmployees;
	}

	public void setDepaEmployees(Set depaEmployees) {
		this.depaEmployees = depaEmployees;
	}

	public Set getDepartEmployees() {
		return this.departEmployees;
	}

	public void setDepartEmployees(Set departEmployees) {
		this.departEmployees = departEmployees;
	}

}
