package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

/**
 * Inventory generated by hbm2java
 */
public class Inventory implements java.io.Serializable {

	private InventoryId id;
	private Product productByPname;
	private Product productByPid;
	private Seller seller;
	private Integer quantity;

	public Inventory() {
	}

	public Inventory(InventoryId id, Product productByPid, Seller seller) {
		this.id = id;
		this.productByPid = productByPid;
		this.seller = seller;
	}

	public Inventory(InventoryId id, Product productByPname, Product productByPid, Seller seller, Integer quantity) {
		this.id = id;
		this.productByPname = productByPname;
		this.productByPid = productByPid;
		this.seller = seller;
		this.quantity = quantity;
	}

	public InventoryId getId() {
		return this.id;
	}

	public void setId(InventoryId id) {
		this.id = id;
	}

	public Product getProductByPname() {
		return this.productByPname;
	}

	public void setProductByPname(Product productByPname) {
		this.productByPname = productByPname;
	}

	public Product getProductByPid() {
		return this.productByPid;
	}

	public void setProductByPid(Product productByPid) {
		this.productByPid = productByPid;
	}

	public Seller getSeller() {
		return this.seller;
	}

	public void setSeller(Seller seller) {
		this.seller = seller;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
