package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Items generated by hbm2java
 */
public class Items implements java.io.Serializable {

	private Integer id;
	private Customers customersByItemsId;
	private Customers customersByItemId;
	private Customers customersByCustomersId;
	private Customers customersByCustomerId;
	private String itemName;
	private Set customersesForItemId = new HashSet(0);
	private Set customersesForCustomerId = new HashSet(0);
	private Set customersesForCustomersId = new HashSet(0);

	public Items() {
	}

	public Items(Customers customersByItemsId, Customers customersByItemId, Customers customersByCustomersId,
			Customers customersByCustomerId, String itemName, Set customersesForItemId, Set customersesForCustomerId,
			Set customersesForCustomersId) {
		this.customersByItemsId = customersByItemsId;
		this.customersByItemId = customersByItemId;
		this.customersByCustomersId = customersByCustomersId;
		this.customersByCustomerId = customersByCustomerId;
		this.itemName = itemName;
		this.customersesForItemId = customersesForItemId;
		this.customersesForCustomerId = customersesForCustomerId;
		this.customersesForCustomersId = customersesForCustomersId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customers getCustomersByItemsId() {
		return this.customersByItemsId;
	}

	public void setCustomersByItemsId(Customers customersByItemsId) {
		this.customersByItemsId = customersByItemsId;
	}

	public Customers getCustomersByItemId() {
		return this.customersByItemId;
	}

	public void setCustomersByItemId(Customers customersByItemId) {
		this.customersByItemId = customersByItemId;
	}

	public Customers getCustomersByCustomersId() {
		return this.customersByCustomersId;
	}

	public void setCustomersByCustomersId(Customers customersByCustomersId) {
		this.customersByCustomersId = customersByCustomersId;
	}

	public Customers getCustomersByCustomerId() {
		return this.customersByCustomerId;
	}

	public void setCustomersByCustomerId(Customers customersByCustomerId) {
		this.customersByCustomerId = customersByCustomerId;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Set getCustomersesForItemId() {
		return this.customersesForItemId;
	}

	public void setCustomersesForItemId(Set customersesForItemId) {
		this.customersesForItemId = customersesForItemId;
	}

	public Set getCustomersesForCustomerId() {
		return this.customersesForCustomerId;
	}

	public void setCustomersesForCustomerId(Set customersesForCustomerId) {
		this.customersesForCustomerId = customersesForCustomerId;
	}

	public Set getCustomersesForCustomersId() {
		return this.customersesForCustomersId;
	}

	public void setCustomersesForCustomersId(Set customersesForCustomersId) {
		this.customersesForCustomersId = customersesForCustomersId;
	}

}
