package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Itm generated by hbm2java
 */
public class Itm implements java.io.Serializable {

	private Integer id;
	private Cust cust;
	private String itemName;
	private Set custs = new HashSet(0);

	public Itm() {
	}

	public Itm(Cust cust, String itemName, Set custs) {
		this.cust = cust;
		this.itemName = itemName;
		this.custs = custs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cust getCust() {
		return this.cust;
	}

	public void setCust(Cust cust) {
		this.cust = cust;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Set getCusts() {
		return this.custs;
	}

	public void setCusts(Set custs) {
		this.custs = custs;
	}

}
