package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private String pid;
	private String pname;
	private String manufacturer;
	private Date mfg;
	private Date exp;
	private Integer price;
	private Set inventoriesForPname = new HashSet(0);
	private Set inventoriesForPid = new HashSet(0);
	private Set orderses = new HashSet(0);

	public Product() {
	}

	public Product(String pid) {
		this.pid = pid;
	}

	public Product(String pid, String pname, String manufacturer, Date mfg, Date exp, Integer price,
			Set inventoriesForPname, Set inventoriesForPid, Set orderses) {
		this.pid = pid;
		this.pname = pname;
		this.manufacturer = manufacturer;
		this.mfg = mfg;
		this.exp = exp;
		this.price = price;
		this.inventoriesForPname = inventoriesForPname;
		this.inventoriesForPid = inventoriesForPid;
		this.orderses = orderses;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public Date getMfg() {
		return this.mfg;
	}

	public void setMfg(Date mfg) {
		this.mfg = mfg;
	}

	public Date getExp() {
		return this.exp;
	}

	public void setExp(Date exp) {
		this.exp = exp;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Set getInventoriesForPname() {
		return this.inventoriesForPname;
	}

	public void setInventoriesForPname(Set inventoriesForPname) {
		this.inventoriesForPname = inventoriesForPname;
	}

	public Set getInventoriesForPid() {
		return this.inventoriesForPid;
	}

	public void setInventoriesForPid(Set inventoriesForPid) {
		this.inventoriesForPid = inventoriesForPid;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
