package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Q generated by hbm2java
 */
public class Q implements java.io.Serializable {

	private Integer id;
	private String question;
	private Set asForQuestId = new HashSet(0);
	private Set asForQuestId_1 = new HashSet(0);

	public Q() {
	}

	public Q(String question, Set asForQuestId, Set asForQuestId_1) {
		this.question = question;
		this.asForQuestId = asForQuestId;
		this.asForQuestId_1 = asForQuestId_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public Set getAsForQuestId() {
		return this.asForQuestId;
	}

	public void setAsForQuestId(Set asForQuestId) {
		this.asForQuestId = asForQuestId;
	}

	public Set getAsForQuestId_1() {
		return this.asForQuestId_1;
	}

	public void setAsForQuestId_1(Set asForQuestId_1) {
		this.asForQuestId_1 = asForQuestId_1;
	}

}
