package com.hibernate.model;
// Generated Jul 25, 2023, 3:27:08 PM by Hibernate Tools 6.0.2.Final

/**
 * StudentCourseId generated by hbm2java
 */
public class StudentCourseId implements java.io.Serializable {

	private int courseId;
	private int studentId;

	public StudentCourseId() {
	}

	public StudentCourseId(int courseId, int studentId) {
		this.courseId = courseId;
		this.studentId = studentId;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentCourseId))
			return false;
		StudentCourseId castOther = (StudentCourseId) other;

		return (this.getCourseId() == castOther.getCourseId()) && (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCourseId();
		result = 37 * result + this.getStudentId();
		return result;
	}

}
